apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homelab-game.fullname" . }}-config
  labels:
    {{- include "homelab-game.labels" . | nindent 4 }}
data:
  DB_HOST: {{ include "homelab-game.fullname" . }}-postgresql
  DB_PORT: {{ .Values.postgresql.port | quote }}
  DB_NAME: {{ .Values.postgresql.database }}
  DB_USER: {{ .Values.postgresql.username }}
  PORT: {{ .Values.backend.env.PORT | quote }}
