apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homelab-game.fullname" . }}-frontend
  labels:
    {{- include "homelab-game.labels" . | nindent 4 }}
    {{- include "homelab-game.frontend.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "homelab-game.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "homelab-game.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: {{ include "homelab-game.frontendImage" . }}
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            periodSeconds: 10
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
