apiVersion: v1
kind: Service
metadata:
  name: {{ include "homelab-game.fullname" . }}-postgresql
  labels:
    {{- include "homelab-game.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None  # headless — stable DNS for StatefulSet
  selector:
    app.kubernetes.io/name: homelab-game-postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
      protocol: TCP
